-- USUARIO
CREATE TABLE USUARIO(
	correo VARCHAR(100) NOT NULL,
	dpi INTEGER NOT NULL,
	nombre VARCHAR(100) NOT NULL,
	fecha_nacimiento TIMESTAMP NOT NULL,
	password VARCHAR(20) NOT NULL,

	CONSTRAINT PK_USUARIO PRIMARY KEY (correo)
);

alter table USUARIO
modify dpi long NOT NULL;

-- SEDE

CREATE TABLE SEDE(
	codigo_sede INTEGER NOT NULL AUTO_INCREMENT,
	alias VARCHAR(50) NOT NULL,
	direccion VARCHAR(150) NOT NULL,
	departamento VARCHAR(50) NOT NULL,
	municipio VARCHAR(50) NOT NULL,
	encargado VARCHAR(100) NOT NULL,

	CONSTRAINT PK_SEDE PRIMARY KEY (codigo_sede),
	CONSTRAINT FK_US FOREIGN KEY (encargado) REFERENCES USUARIO(correo)
);

-- CLIENTE
CREATE TABLE CLIENTE(
	nit VARCHAR(20) NOT NULL,
	nombre VARCHAR(100) NOT NULL,
	dpi INTEGER NOT NULL,
	direccion VARCHAR(150) NOT NULL,

	CONSTRAINT PK_CLIENTE PRIMARY KEY (nit)
);

alter table CLIENTE
modify dpi long NOT NULL;

-- SEDE CLIENTE
CREATE TABLE SEDE_CLIENTE(
	sede INTEGER NOT NULL,
	nit VARCHAR(20) NOT NULL,

	CONSTRAINT PK_SEDE_CLIENTE PRIMARY KEY (sede, nit),
	CONSTRAINT FK_S_SC FOREIGN KEY (sede) REFERENCES SEDE(codigo_sede),
	CONSTRAINT FK_C_SC FOREIGN KEY (nit) REFERENCES CLIENTE(nit)
);

-- ROL

CREATE TABLE ROL(
	rol INTEGER NOT NULL,
	nombre VARCHAR(20) NOT NULL,

	CONSTRAINT PK_ROL PRIMARY KEY (rol)
);

-- PERMISO

CREATE TABLE PERMISO(
	permiso INTEGER NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	rol INTEGER NOT NULL,

	CONSTRAINT PK_PERMISO PRIMARY KEY (permiso),
	CONSTRAINT FK_R_P FOREIGN KEY (rol) REFERENCES ROL(rol)
);

-- ROL USUARIO

CREATE TABLE ROL_USUARIO(
	rol INTEGER NOT NULL,
	correo VARCHAR(100) NOT NULL,

	CONSTRAINT PK_ROL_USER PRIMARY KEY (rol,correo),
	CONSTRAINT FK_R_RU FOREIGN KEY (rol) REFERENCES ROL(rol),
	CONSTRAINT FK_U_RU FOREIGN KEY (correo) REFERENCES USUARIO(correo)
);

-- CATEGORIA

CREATE TABLE CATEGORIA(
	categoria INTEGER NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(50) NOT NULL,

	CONSTRAINT PK_CATEGORIA PRIMARY KEY (categoria)
);

-- PRODUCTO

CREATE TABLE PRODUCTO(
	sku INTEGER NOT NULL,
	codigo_barras VARCHAR(200) NOT NULL,
	nombre VARCHAR(50) NOT NULL,
	descripcion VARCHAR(200) NOT NULL,
	precio DECIMAL(10,2) NOT NULL,

	CONSTRAINT PK_PRODUCTO PRIMARY KEY (sku)
);

CREATE TABLE CATEGORIA_PRODUCTO(
	categoria INTEGER NOT NULL,
	sku INTEGER NOT NULL,

	CONSTRAINT PK_CP PRIMARY KEY (categoria, sku),
	CONSTRAINT FK_C_CP FOREIGN KEY (categoria) REFERENCES CATEGORIA(categoria),
	CONSTRAINT FK_P_CP FOREIGN KEY (sku) REFERENCES PRODUCTO(sku)
);

-- BODEGA

CREATE TABLE BODEGA(
	codigo_bodega INTEGER NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(50) NOT NULL,
	direccion VARCHAR(100) NOT NULL,
	estado VARCHAR(1) NOT NULL,
	encargado VARCHAR(100) NOT NULL,

	CONSTRAINT PK_BODEGA PRIMARY KEY (codigo_bodega),
	CONSTRAINT FK_U_B FOREIGN KEY (encargado) REFERENCES USUARIO(correo)
);

-- INVENTARIO

CREATE TABLE INVENTARIO(
	codigo_inventario INTEGER NOT NULL AUTO_INCREMENT,
	motivo VARCHAR(250) NOT NULL,
	fecha TIMESTAMP NOT NULL,
	bodega INTEGER NOT NULL,
	usuario VARCHAR(100) NOT NULL,

	CONSTRAINT PK_INVENTARIO PRIMARY KEY (codigo_inventario),
	CONSTRAINT FK_B_I FOREIGN KEY (bodega) REFERENCES BODEGA(codigo_bodega),
	CONSTRAINT FK_U_I FOREIGN KEY (usuario) REFERENCES USUARIO(correo)
);

-- DETALLE INVENTARIO

CREATE TABLE DETALLE_INVENTARIO(
	codigo_dt_in INTEGER NOT NULL AUTO_INCREMENT,
	producto INTEGER NOT NULL,
	cantidad_antigua INTEGER NOT NULL,
	cantidad_nueva INTEGER NOT NULL,
	inventario INTEGER NOT NULL,

	CONSTRAINT PK_DT_INV PRIMARY KEY (codigo_dt_in),
	CONSTRAINT FK_P_DT FOREIGN KEY (producto) REFERENCES PRODUCTO(sku),
	CONSTRAINT FK_I_DT FOREIGN KEY (inventario) REFERENCES INVENTARIO(codigo_inventario)
);

-- TRANSFERENCIA

CREATE TABLE TRANSFERENCIA(
	codigo_transferencia INTEGER NOT NULL AUTO_INCREMENT,
	tipo_transferencia VARCHAR(1) NOT NULL,
	estado_transferencia VARCHAR(1) NOT NULL,

	producto INTEGER NOT NULL,
	cantidad_saliente INTEGER NOT NULL,

	usuario_acepta VARCHAR(100) NOT NULL,
	repartidor VARCHAR(100) NOT NULL,

	sede_origen INTEGER NOT NULL,
	sede_destino INTEGER NOT NULL,

	bodega_origen INTEGER NOT NULL,
	bodega_destino INTEGER NOT NULL,

	CONSTRAINT PK_TRANSFERENCIA PRIMARY KEY (codigo_transferencia),
	CONSTRAINT FK_P_TRAN FOREIGN KEY (producto) REFERENCES PRODUCTO(sku),
	CONSTRAINT FK_U_TRAN FOREIGN KEY (usuario_acepta) REFERENCES USUARIO(correo),
	CONSTRAINT FK_R_TRAN FOREIGN KEY (repartidor) REFERENCES USUARIO(correo),
	CONSTRAINT FK_SO_TRAN FOREIGN KEY (sede_origen) REFERENCES SEDE(codigo_sede),
	CONSTRAINT FK_SD_TRAN FOREIGN KEY (sede_destino) REFERENCES SEDE(codigo_sede),
	CONSTRAINT FK_BO_TRAN FOREIGN KEY (bodega_origen) REFERENCES BODEGA(codigo_bodega),
	CONSTRAINT FK_BD_TRAN FOREIGN KEY (bodega_destino) REFERENCES BODEGA(codigo_bodega)
);

-- VENTA

CREATE TABLE VENTA(
	codigo_venta INTEGER NOT NULL AUTO_INCREMENT,
	vendedor VARCHAR(100) NULL,
	cliente VARCHAR(20) NOT NULL,
	fecha_factura TIMESTAMP NOT NULL,
	fecha_entrega TIMESTAMP NULL,
	subtotal DECIMAL(10,2) NOT NULL,
	repartidor VARCHAR(100) NULL,
	tipo_venta VARCHAR(1) NOT NULL,
	sobre_cargo DECIMAL(10,2) NOT NULL,
	total DECIMAL(10,2) NOT NULL,

	CONSTRAINT PK_VENTA PRIMARY KEY (codigo_venta),
	CONSTRAINT FK_U_VENTA FOREIGN KEY (vendedor) REFERENCES USUARIO(correo),
	CONSTRAINT FK_C_VENTA FOREIGN KEY (cliente) REFERENCES CLIENTE(nit),
	CONSTRAINT FK_R_VENTA FOREIGN KEY (repartidor) REFERENCES USUARIO(correo)
);

CREATE TABLE DETALLE_VENTA (
	detalle_venta INTEGER NOT NULL AUTO_INCREMENT,
    descuento INTEGER NULL,
    producto INTEGER NOT NULL,
    venta INTEGER NOT NULL,
    
    CONSTRAINT PK_DETALLEVENTA PRIMARY KEY (detalle_venta),
	CONSTRAINT FK_V_DTVENTA FOREIGN KEY (venta) REFERENCES VENTA(codigo_venta),
	CONSTRAINT FK_P_DTVENTA FOREIGN KEY (producto) REFERENCES PRODUCTO(sku)
);